- name: Configure an openwrt router
  hosts: openwrt
  gather_facts: no

  roles:
    - gekmihesg.openwrt

  tasks:

    - name: "Check if host is a docker container"
      stat:
        path: "/.dockerenv"
      register: host_is_container

    - name: Install packages
      opkg:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop: '{{ packages.install }}'
      loop_control:
        label: Installing {{ item }}

    - name: Set cpufreq governor to ondemand in rc.local
      lineinfile:
        path: /etc/rc.local
        insertbefore: '^exit 0$'
        line: 'echo ondemand > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor'

    - name: Enable Wireless Ethernet Dispatch (WED)
      lineinfile:
        path: /etc/modules.d/mt7915e
        regex: '^mt7915e'
        line: 'mt7915e wed_enable=Y'

    - name: Create /etc/config/network
      template:
        src: 'config/network'
        dest: '/etc/config/network'
      notify: Reload network

    - name: Create /etc/config/wireless
      template:
        src: 'config/wireless'
        dest: '/etc/config/wireless'
      notify: Reload wifi

    - name: Create /etc/config/firewall
      template:
        src: 'config/firewall'
        dest: '/etc/config/firewall'
      notify: Reload firewall

    - name: Create /etc/config/dhcp
      template:
        src: 'config/dhcp'
        dest: '/etc/config/dhcp'
      notify: Restart dhcp

  handlers:

    - name: Reload network
      nohup:
        command: /etc/init.d/network reload
        delay: 1
      when:
        - "'openwrt' in group_names"
        - host_is_container != true

    - name: Reload wifi
      nohup:
        command: /sbin/wifi reload
        delay: 1
      when:
        - "'openwrt' in group_names"
        - host_is_container != true

    - name: Reload firewall
      nohup:
        command: /etc/init.d/firewall reload
        delay: 1
      when:
        - "'openwrt' in group_names"
        - host_is_container != true

    - name: Restart dhcp
      nohup:
        command: /etc/init.d/dnsmasq restart
        delay: 1
      when:
        - "'openwrt' in group_names"
        - host_is_container != true

    - name: Wait for connection
      wait_for_connection:
        timeout: "{{ openwrt_wait_for_connection_timeout }}"
        delay: 5
      when:
        - "'openwrt' in group_names"
        - openwrt_wait_for_connection
      listen:
        - Reload network
        - Reload wifi
        - Reload firewall
        - Restart dhcp
